server:
  port: 9090
###
spring:
  application:
    name: REST-API-SERVICE-HIERARCY-MYSQL
###
eureka:
  client:
    service-url: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost